### ISSUE TITLE
Your Website is dead. Totally.

### ISSUE THREAD

**Issue by MizuNoNakaniwa** [kchambit/readera-cites#2]
I don't know if it's because my notes are Chinese, but anyway, when I put the json file in, it doesn't show more, it's blank. So I think your page should be dead.

**Comment by MizuNoNakaniwa** [comment]
If you don't want to fix website, could you tell me how this code works locally? I have python on my computer but I don't know how to use it, thanks.

**Comment by croko22** [comment]
> I don't know if it's because my notes are Chinese, but anyway, when I put the json file in, it doesn't show more, it's blank. So I think your page should be dead.

How is the structure of your json file

I tested mine recently and it worked fine, so I'm guessing it might be a format issue.

![image_2024-07-13_191123703](https://github.com/user-attachments/assets/10c949e9-6464-4c90-80c6-b4a66f2f1e08)

**Comment by croko22** [comment]
> If you don't want to fix website, could you tell me how this code works locally? I have python on my computer but I don't know how to use it, thanks.

Make sure you have Node.js installed
npm install (This installs all the project dependencies listed in the package.json file.)
npm run dev (This starts the development server and usually opens your app in the browser at http://localhost:3000/.)

**Comment by MizuNoNakaniwa** [comment]
> > I don't know if it's because my notes are Chinese, but anyway, when I put the json file in, it doesn't show more, it's blank. So I think your page should be dead.
> 
> How is the structure of your json file
> 
> I tested mine recently and it worked fine, so I'm guessing it might be a format issue.
> 
> ![image_2024-07-13_191123703](https://private-user-images.githubusercontent.com/77868280/348509078-10c949e9-6464-4c90-80c6-b4a66f2f1e08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5OTg3ODYsIm5iZiI6MTcyMDk5ODQ4NiwicGF0aCI6Ii83Nzg2ODI4MC8zNDg1MDkwNzgtMTBjOTQ5ZTktNjQ2NC00YzkwLTgwYzYtYjRhNjZmMmYxZTA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE0VDIzMDgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3NmQyMDE4MTA3NmEyYmRlYzE1NzE5ZjY1MTI4MDdjNGEwNmE4MDM3MzJhNjc1YTZjMmUyZDQwNTQ3YmM2YjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XWGJqheOu6M2PPOhp1FX3wVxRxCq0L8NKS-OhWTwKKk)

Uhhhh. I dont know tbh, because I basically have 0 idea how its works.... I think its Chinese language problem (im not sure).
I know its sounds like rude, but how about I send you my data package, could you help me to test it? Thank you! 

[library.json](https://github.com/user-attachments/files/16229078/library.json)

**Comment by MizuNoNakaniwa** [comment]
> > If you don't want to fix website, could you tell me how this code works locally? I have python on my computer but I don't know how to use it, thanks.
> 
> Make sure you have Node.js installed npm install (This installs all the project dependencies listed in the package.json file.) npm run dev (This starts the development server and usually opens your app in the browser at http://localhost:3000/.)

Hey croko22, Thanks dude! It's all solved. Peace.🙏
